### ISSUE TITLE
Well package error

### ISSUE THREAD

**Issue by jakubriha85** [lanl/dfnWorks#55]
I am trying to use Well Package in DFNWorks V2.7 (alannah Docker Image) and it is crashing with the following error (it does so with both my task and GitHub master example problem well_example): 

--> Working on well inject
--> Interpolating well coordinates into a polyline
--> Interpolating well coordinates into a polyline: Complete
--> Writing polyline into avs file : well_inject_line.inp
--> Writing polyline into avs file : well_inject_line.inp : Complete
Traceback (most recent call last):
  File "/dfnWorks/work/[driver.py](https://urldefense.com/v3/__http:/driver.py__;!!Bt8fGhp8LhKGRg!BDIOHHWl78Q6Ga1iRVUWxfmwDrvoQXPxegO5rzvIjIfGRprEc9fjkQqOdLfvkkGDNra0r1FajWcRd6HHg7Jr$)", line 86, in <module>
    DFN.find_well_intersection_points(wells)
  File "/usr/local/lib/python3.10/dist-packages/pydfnworks-2.7-py3.10.egg/pydfnworks/dfnGen/well_package/[wells.py](https://urldefense.com/v3/__http:/wells.py__;!!Bt8fGhp8LhKGRg!BDIOHHWl78Q6Ga1iRVUWxfmwDrvoQXPxegO5rzvIjIfGRprEc9fjkQqOdLfvkkGDNra0r1FajWcRd46rrwQ8$)", line 590, in find_well_intersection_points
    run_find_well_intersection_points(well, self.h)
  File "/usr/local/lib/python3.10/dist-packages/pydfnworks-2.7-py3.10.egg/pydfnworks/dfnGen/well_package/[wells.py](https://urldefense.com/v3/__http:/wells.py__;!!Bt8fGhp8LhKGRg!BDIOHHWl78Q6Ga1iRVUWxfmwDrvoQXPxegO5rzvIjIfGRprEc9fjkQqOdLfvkkGDNra0r1FajWcRd46rrwQ8$)", line 637, in run_find_well_intersection_points
    find_segments(well)
  File "/usr/local/lib/python3.10/dist-packages/pydfnworks-2.7-py3.10.egg/pydfnworks/dfnGen/well_package/[wells.py](https://urldefense.com/v3/__http:/wells.py__;!!Bt8fGhp8LhKGRg!BDIOHHWl78Q6Ga1iRVUWxfmwDrvoQXPxegO5rzvIjIfGRprEc9fjkQqOdLfvkkGDNra0r1FajWcRd46rrwQ8$)", line 791, in find_segments
    mh.run_lagrit_script(f"find_well_{well['name']}_segment.lgi",
NameError: name 'mh' is not defined

**Comment by hymanjd** [comment]
Hi Jakub, 

I just pushed a patch. Please pull, rebuild and try again. Let me know how it goes. 

J

**Comment by jakubriha85** [comment]
Hi,
It seems to be working. Thank You for the fix.
Jakub
