### ISSUE TITLE
Logger Error with object deconstructor

### ISSUE THREAD

**Issue by aksitchler** [lanl/dfnWorks#95]
I'm getting this error when a DFN object goes out of scope

Exception ignored in: <function DFNWORKS.__del__ at 0x168b56160>
Traceback (most recent call last):
  File "/Users/alexissitchler/Library/Python/3.9/lib/python/site-packages/pydfnworks/general/dfnworks.py", line 232, in __del__
  File "/Users/alexissitchler/Library/Python/3.9/lib/python/site-packages/pydfnworks/general/logging.py", line 54, in print_log
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/logging/__init__.py", line 2097, in info
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/logging/__init__.py", line 1446, in info
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/logging/__init__.py", line 1589, in _log
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/logging/__init__.py", line 1599, in handle
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/logging/__init__.py", line 1661, in callHandlers
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/logging/__init__.py", line 952, in handle
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/logging/__init__.py", line 1186, in emit
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/logging/__init__.py", line 1175, in _open
LookupError: unknown encoding: ascii

**Comment by hymanjd** [comment]
@ehinrichs  can you look into this?

**Comment by hymanjd** [comment]
Fixed. `DFNWORKS.__del__` no longer routes through the logging handlers, which is what raised `LookupError: unknown encoding: ascii` during interpreter teardown. It now uses a plain guarded `print`:

```python
def __del__(self):
    try:
        print(f"--> {self.local_jobname} completed/exited ")
    except Exception:
        print("--> Job completed/exited")
```

Closing as resolved.
