### ISSUE TITLE
Indexing fractures outside domain

### ISSUE THREAD

**Issue by aksitchler** [lanl/dfnWorks#97]
When I set domainSizeIncrease to something greater than zero I get the following error: 

--> Gathering points on fractures
Traceback (most recent call last):
  File "/Users/alexissitchler/software/dfnWorks/examples/chem_lognormal/driver.py", line 80, in <module>
    DFN.map_to_continuum(l=1.5, orl=3)
  File "/Users/alexissitchler/Library/Python/3.9/lib/python/site-packages/pydfnworks/dfnGen/meshing/udfm/map2continuum.py", line 92, in map_to_continuum
    points = self.gather_points()
  File "/Users/alexissitchler/Library/Python/3.9/lib/python/site-packages/pydfnworks/dfnGen/meshing/udfm/map2continuum_helper.py", line 73, in gather_points
    point = self.polygons[name][j]
IndexError: index 5 is out of bounds for axis 0 with size 5
--> output_chem_lognormal completed/exited

**Comment by hymanjd** [comment]
Can you also post your whole input card?

**Comment by aksitchler** [comment]
#"""
#   :synopsis: Driver run file for TPL example
#   :version: 2.0
#   :maintainer: Jeffrey Hyman
#.. moduleauthor:: Jeffrey Hyman <jhyman@lanl.gov>
#"""

from pydfnworks import *
import os

src_path = os.getcwd()
jobname = src_path + "/output_chem_lognormal"
dfnFlow_file = src_path + '/chem_lognormal.in'

DFN = DFNWORKS(jobname,
               dfnFlow_file=dfnFlow_file,
               flow_solver="PFLOTRAN",
               ncpu=8)

DFN.params['domainSize']['value'] = [5, 5, 5]
DFN.params['h']['value'] = 0.15
DFN.params['stopCondition']['value'] = 0
DFN.params['nPoly']['value'] = 25
DFN.params['outputFinalRadiiPerFamily']['value'] = True
DFN.params['outputAcceptedRadiiPerFamily']['value'] = True
DFN.params['forceLargeFractures']['value'] = True
DFN.params['domainSizeIncrease']['value'] = [1, 1, 1]
DFN.params['ignoreBoundaryFaces']['value'] = False
DFN.params['boundaryFaces']['value'] = [0, 0, 0, 0, 1, 1]
DFN.params['rejectsPerFracture']['value'] = 350
DFN.params['visualizationMode']['value'] = True

DFN.add_fracture_family(shape="rect",
                        distribution="log_normal",
                        kappa=25.78,
                        probability=.5,
                        aspect=1.0,
                        beta_distribution=1,
                        beta=0.0,
                        theta=95.47,
                        phi=23.32,
                        log_mean=0.5,
                        log_std=.06,
                        min_radius=0.5,
                        max_radius=5.0,
                        hy_variable="permeability",
                        hy_function="correlated",
                        hy_params={
                            "alpha": 1e-7,
                            "beta": 2
                        })

DFN.add_fracture_family(shape="rect",
                        distribution="log_normal",
                        kappa=32.0,
                        probability=.5,
                        aspect=1.0,
                        beta_distribution=1,
                        beta=0.0,
                        theta=1.42,
                        phi=26.81,
                        log_mean=0.3,
                        log_std=.06,
                        min_radius=0.5,
                        max_radius=5.0,
                        hy_variable="permeability",
                        hy_function="correlated",
                        hy_params={
                            "alpha": 1e-7,
                            "beta": 2
                        })

DFN.make_working_directory(delete=True)
DFN.check_input()
# define_paths()
DFN.create_network()
#DFN.output_report()
DFN.mesh_network()

DFN.map_to_continuum(l=1.5, orl=3)
DFN.upscale(mat_perm=1e-17, mat_por=0.01)

DFN.zone2ex(zone_file='all')
DFN.material_ids = np.genfromtxt('tag_frac.dat').astype(int)

**Comment by hymanjd** [comment]
Was able to reproduce error. Thanks!

From: aksitchler ***@***.***>
Reply-To: lanl/dfnWorks ***@***.***>
Date: Thursday, December 19, 2024 at 3:52 PM
To: lanl/dfnWorks ***@***.***>
Cc: Jeffrey Hyman ***@***.***>, Comment ***@***.***>
Subject: [EXTERNAL] Re: [lanl/dfnWorks] Indexing fractures outside domain (Issue #97)


#"""

:synopsis: Driver run file for TPL example
:version: 2.0
:maintainer: Jeffrey Hyman

#.. moduleauthor:: Jeffrey Hyman ***@***.******@***.***>
#"""

from pydfnworks import *
import os

src_path = os.getcwd()
jobname = src_path + "/output_chem_lognormal"
dfnFlow_file = src_path + '/chem_lognormal.in<https://urldefense.com/v3/__http:/chem_lognormal.in__;!!Bt8fGhp8LhKGRg!F63fHS83ylc1HwchkfaWbr_TShCUB-E6c9u17H5d1Sjvzzx6b5FWg0QsDrrYoCsS1SwJL3Au7k0eDpugOAMoKM5Z$>'

DFN = DFNWORKS(jobname,
dfnFlow_file=dfnFlow_file,
flow_solver="PFLOTRAN",
ncpu=8)

DFN.params['domainSize']['value'] = [5, 5, 5]
DFN.params['h']['value'] = 0.15
DFN.params['stopCondition']['value'] = 0
DFN.params['nPoly']['value'] = 25
DFN.params['outputFinalRadiiPerFamily']['value'] = True
DFN.params['outputAcceptedRadiiPerFamily']['value'] = True
DFN.params['forceLargeFractures']['value'] = True
DFN.params['domainSizeIncrease']['value'] = [1, 1, 1]
DFN.params['ignoreBoundaryFaces']['value'] = False
DFN.params['boundaryFaces']['value'] = [0, 0, 0, 0, 1, 1]
DFN.params['rejectsPerFracture']['value'] = 350
DFN.params['visualizationMode']['value'] = True

DFN.add_fracture_family(shape="rect",
distribution="log_normal",
kappa=25.78,
probability=.5,
aspect=1.0,
beta_distribution=1,
beta=0.0,
theta=95.47,
phi=23.32,
log_mean=0.5,
log_std=.06,
min_radius=0.5,
max_radius=5.0,
hy_variable="permeability",
hy_function="correlated",
hy_params={
"alpha": 1e-7,
"beta": 2
})

DFN.add_fracture_family(shape="rect",
distribution="log_normal",
kappa=32.0,
probability=.5,
aspect=1.0,
beta_distribution=1,
beta=0.0,
theta=1.42,
phi=26.81,
log_mean=0.3,
log_std=.06,
min_radius=0.5,
max_radius=5.0,
hy_variable="permeability",
hy_function="correlated",
hy_params={
"alpha": 1e-7,
"beta": 2
})

DFN.make_working_directory(delete=True)
DFN.check_input()

define_paths()

DFN.create_network()
#DFN.output_report()
DFN.mesh_network()

DFN.map_to_continuum(l=1.5, orl=3)
DFN.upscale(mat_perm=1e-17, mat_por=0.01)

DFN.zone2ex(zone_file='all')
DFN.material_ids = np.genfromtxt('tag_frac.dat').astype(int)

**Comment by hymanjd** [comment]
Fixed in `1dc06aa0` (#98). `gather_points()` no longer walks the vertex index past the end of the polygon array: the loop is now bounded by `for j in range(num_pts)` with an explicit `found` flag, and the case where no vertex lies inside the domain reports a clear error instead of raising `IndexError`.

See `pydfnworks/dfnGen/meshing/udfm/map2continuum_helper.py`. Closing as resolved -- please reopen if you still hit this with a current checkout.
